name: surdmc-landing-page
region: fra

static_sites:
  - name: surdmc-static
    github:
      repo: LetsUpdate/SurdMCLandingPage
      branch: main
      deploy_on_push: true
    build_command: git lfs install && git lfs pull
    output_dir: public
    catchall_document: index.html
    error_document: index.html
