name: surdmc-landing-page
region: fra

static_sites:
  - name: surdmc-static
    github:
      repo: LetsUpdate/SurdMCLandingPage
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: /public
    catchall_document: index.html
    error_document: index.html
    routes:
      - path: /
    environment_slug: html
